# Generated by Django 2.2.17 on 2021-03-29 20:16

from django.db import migrations, models
import django.db.models.deletion
import mysite.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='作者名', max_length=20)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('phone_number', models.BigIntegerField()),
            ],
            options={
                'verbose_name': '作者信息表',
                'db_table': 'tbl_author',
                'unique_together': {('name', 'phone_number')},
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'verbose_name': '书籍信息表',
                'db_table': 'tbl_book',
            },
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('test', models.BigIntegerField(default=0)),
                ('time_field', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '出版社信息表',
                'db_table': 'tbl_publish',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=mysite.models.UUIDTools.uuid4_hex)),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('mobile', models.CharField(blank=True, max_length=11, unique=True)),
                ('email', models.EmailField(blank=True, max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'user信息表',
                'db_table': 'tbl_user',
            },
        ),
        migrations.CreateModel(
            name='BookRelatedAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=50)),
                ('author_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Author')),
                ('book_id', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='mysite.Book')),
            ],
            options={
                'verbose_name': '书籍信息表',
                'db_table': 'tbl_book_related_author',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='authors', through='mysite.BookRelatedAuthor', to='mysite.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='publisher', to='mysite.Publish'),
        ),
    ]
