# Generated by Django 2.2.17 on 2021-04-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20210329_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='VueModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'vue信息表',
                'db_table': 'tbl_vue',
            },
        ),
    ]
