# Generated by Django 2.2.17 on 2021-05-17 16:58

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_vuemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=10)),
                ('base_url', models.CharField(max_length=500)),
                ('params', models.CharField(default='', max_length=500, null=True)),
                ('headers', django_mysql.models.JSONField(default=dict, null=True)),
                ('mine_type', models.CharField(max_length=5)),
                ('body', django_mysql.models.JSONField(default=dict, null=True)),
                ('response', django_mysql.models.JSONField(default=dict, null=True)),
            ],
            options={
                'verbose_name': '接口用例表',
                'db_table': 'tbl_case_info',
            },
        ),
        migrations.CreateModel(
            name='VueUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('roletype', models.CharField(default='普通用户', max_length=20)),
            ],
            options={
                'verbose_name': 'user信息表',
                'db_table': 'internal_user',
            },
        ),
    ]
