# Generated by Django 3.2.3 on 2021-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20210517_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='params',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
