# Generated by Django 3.2.3 on 2021-05-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_testcase_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='base_url',
            new_name='url',
        ),
    ]
