# Generated by Django 3.2.3 on 2021-05-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_rename_base_url_testcase_url'),
    ]

    operations = [

    ]
