# Generated by Django 3.2.3 on 2021-05-18 11:51

from django.db import migrations, models
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20210518_1137'),
    ]

    operations = [

    ]
