# Generated by Django 3.2.3 on 2021-05-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20210518_1151'),
    ]

    operations = [

    ]
