# Generated by Django 3.2.3 on 2021-05-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20210518_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='body',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='headers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='response',
            field=models.JSONField(null=True),
        ),
    ]
