# Generated by Django 3.2.3 on 2021-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20210518_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vuemodel',
            name='age',
            field=models.IntegerField(),
        ),
    ]
