# Generated by Django 3.2.2 on 2021-06-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20210603_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSuiteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_ids', models.JSONField()),
            ],
            options={
                'db_table': 'tbl_runsuite_record',
            },
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'ordering': ['id'], 'verbose_name': '出版社信息表'},
        ),
    ]
