# Generated by Django 3.2.2 on 2021-06-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20210605_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='error_msg',
            field=models.JSONField(null=True),
        ),
    ]
