# Generated by Django 3.2.2 on 2021-06-05 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_rename_case_ids_runsuiterecord_suite_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variablesglobal',
            options={'verbose_name': '全局变量表'},
        ),
        migrations.AlterModelTable(
            name='variablesglobal',
            table='tbl_global_variables',
        ),
    ]
