# Generated by Django 3.2.2 on 2021-06-06 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0021_auto_20210605_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variablesglobal',
            options={'ordering': ['id'], 'verbose_name': '全局变量表'},
        ),
        migrations.AddField(
            model_name='variablesglobal',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variablesglobal',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
