# Generated by Django 3.2.2 on 2021-06-08 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_auto_20210606_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testcase',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
