# Generated by Django 3.2.2 on 2021-06-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_auto_20210608_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcase',
            options={'ordering': ['id'], 'verbose_name': '接口用例表'},
        ),
        migrations.AlterModelOptions(
            name='testsuite',
            options={'ordering': ['id'], 'verbose_name': '接口套件表'},
        ),
        migrations.AlterField(
            model_name='variablesglobal',
            name='variable_value',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
