# Generated by Django 3.2.2 on 2021-06-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0024_auto_20210610_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='bookrelatedauthor',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bookrelatedauthor',
            name='book',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='VueModel',
        ),
        migrations.DeleteModel(
            name='VueUserModel',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookRelatedAuthor',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
