# Generated by Django 3.2.2 on 2021-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0025_auto_20210612_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(max_length=50)),
                ('schedule_type', models.CharField(choices=[('1', '按日期执行'), ('2', '间隔周期执行'), ('3', 'cron 定时器执行')], max_length=10)),
                ('schedule_time', models.CharField(max_length=50)),
                ('enable', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
