# Generated by Django 3.2.2 on 2021-06-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0026_scheduletrigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletrigger',
            options={'verbose_name': '定时任务表'},
        ),
        migrations.AlterModelTable(
            name='scheduletrigger',
            table='tbl_schedule',
        ),
    ]
