# Generated by Django 3.2.2 on 2021-06-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0027_auto_20210613_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduletrigger',
            name='schedule_args',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
