# Generated by Django 3.2.2 on 2021-06-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0028_scheduletrigger_schedule_args'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduletrigger',
            options={'ordering': ['id'], 'verbose_name': '定时任务表'},
        ),
        migrations.AddField(
            model_name='testcase',
            name='project_name',
            field=models.CharField(default='供应链', max_length=50),
            preserve_default=False,
        ),
    ]
