# Generated by Django 3.2.2 on 2021-06-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0030_projectconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='project_name',
        ),
        migrations.AddField(
            model_name='testcase',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
