# Generated by Django 3.2.2 on 2021-07-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0032_rename_case_id_testsuite_cases_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsuiterecord',
            name='taskid',
            field=models.UUIDField(default=134444),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'mobile')},
        ),
    ]
