# Generated by Django 3.2.2 on 2021-07-27 17:52

from django.db import migrations, models
import django.utils.timezone
import mysite.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0033_auto_20210727_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='runsuiterecord',
            name='create_by',
            field=models.CharField(default='系统', max_length=50),
        ),
        migrations.AddField(
            model_name='runsuiterecord',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='runsuiterecord',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='runsuiterecord',
            name='taskid',
            field=models.UUIDField(default=mysite.models.UUIDTools.uuid4_hex),
        ),
    ]
