# Generated by Django 3.2.2 on 2021-07-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0034_auto_20210727_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExcuteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.UUIDField()),
                ('suite_id', models.IntegerField()),
                ('case_id', models.IntegerField()),
                ('case_name', models.CharField(max_length=50, unique=True)),
                ('project_id', models.IntegerField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=500)),
                ('params', models.CharField(max_length=500, null=True)),
                ('headers', models.JSONField(null=True)),
                ('mine_type', models.CharField(max_length=5)),
                ('body', models.JSONField(null=True)),
                ('response', models.JSONField(null=True)),
                ('extract', models.JSONField(null=True)),
                ('assert_express', models.JSONField(null=True)),
                ('error_msg', models.JSONField(null=True)),
                ('status', models.CharField(default='0', max_length=20)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
