# Generated by Django 3.2.2 on 2021-07-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0036_auto_20210728_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskexcuterecord',
            name='case_name',
            field=models.CharField(max_length=50),
        ),
    ]
