# Generated by Django 3.2.2 on 2021-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0037_alter_taskexcuterecord_case_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runsuiterecord',
            options={'ordering': ['-create_time']},
        ),
        migrations.AddField(
            model_name='runsuiterecord',
            name='status',
            field=models.CharField(choices=[('0', '未执行'), ('1', '执行失败'), ('2', '执行成功')], default='0', max_length=10),
        ),
    ]
