# Generated by Django 3.2.2 on 2021-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0040_roleinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleinfo',
            name='role_type',
            field=models.CharField(choices=[('0', '普通角色'), ('1', '管理员')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='roleinfo',
            name='status',
            field=models.CharField(choices=[('0', '禁用'), ('1', '启用')], default=1, max_length=10),
        ),
    ]
